node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'ngocphupham/ identity-provider') {
       def app = docker.build("ngocphupham/identity-provider:${commit_id}", '.').push()
     }
   }
  stage('deploy'){

    sshagent(['vinhphan-root-keys']) {
      docker.withRegistry('https://index.docker.io/v2/', 'ngocphupham/ identity-provider') {
        def app = docker.image("ngocphupham/identity-provider:${commit_id}").push()
        sh "docker pull ngocphupham/identity-provider:${commit_id}"
        sh 'docker ps -a | grep high3ar-identity-provider && docker stop high3ar-identity-provider && docker rm high3ar-identity-provider || echo "No container found to stop"'
        sh "docker run -d --name high3ar-identity-provider --env-file .env.production.highbar -p 3002:3002 ngocphupham/identity-provider:${commit_id}"
      }
    }

  }
}

docker run --name remote-host remote-host
